import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: [
          "var(--font-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "monospace",
        ],
      },
      fontSize: {
        /* Échelle CRÉO (ne remplace pas les text-* Tailwind par défaut) */
        "creo-xs": ["11px", { lineHeight: "1.4" }],
        "creo-sm": ["13px", { lineHeight: "1.5" }],
        "creo-base": ["14px", { lineHeight: "1.6" }],
        "creo-md": ["15px", { lineHeight: "1.6" }],
        "creo-lg": ["18px", { lineHeight: "1.5" }],
        "creo-xl": ["22px", { lineHeight: "1.4" }],
        "creo-2xl": ["28px", { lineHeight: "1.3" }],
        "creo-3xl": ["36px", { lineHeight: "1.2" }],
      },
      spacing: {
        "creo-1": "var(--creo-space-1)",
        "creo-2": "var(--creo-space-2)",
        "creo-3": "var(--creo-space-3)",
        "creo-4": "var(--creo-space-4)",
        "creo-5": "var(--creo-space-5)",
        "creo-6": "var(--creo-space-6)",
        "creo-8": "var(--creo-space-8)",
        "creo-10": "var(--creo-space-10)",
        "creo-12": "var(--creo-space-12)",
        "creo-16": "var(--creo-space-16)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "creo-sm": "var(--creo-radius-sm)",
        "creo-md": "var(--creo-radius-md)",
        "creo-lg": "var(--creo-radius-lg)",
        "creo-xl": "var(--creo-radius-xl)",
        "creo-full": "var(--creo-radius-full)",
      },
      boxShadow: {
        creo: "var(--creo-shadow-elevated)",
        "creo-card": "var(--creo-shadow-card-hover)",
        "creo-modal": "var(--creo-shadow-modal)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        creo: {
          blue: "var(--creo-blue)",
          "blue-soft": "var(--creo-blue-soft)",
          "blue-deep": "var(--creo-blue-deep)",
          teal: "var(--creo-teal)",
          purple: "var(--creo-purple)",
          "purple-light": "var(--creo-purple-light)",
          "purple-pale": "var(--creo-purple-pale)",
          "purple-dark": "var(--creo-purple-dark)",
          black: "var(--creo-black)",
          gray: {
            50: "var(--creo-gray-50)",
            100: "var(--creo-gray-100)",
            200: "var(--creo-gray-200)",
            300: "var(--creo-gray-300)",
            400: "var(--creo-gray-400)",
            500: "var(--creo-gray-500)",
            700: "var(--creo-gray-700)",
            900: "var(--creo-gray-900)",
          },
          white: "var(--creo-white)",
          success: "var(--creo-success)",
          "success-pale": "var(--creo-success-pale)",
          warning: "var(--creo-warning)",
          "warning-pale": "var(--creo-warning-pale)",
          danger: "var(--creo-danger)",
          "danger-pale": "var(--creo-danger-pale)",
          info: "var(--creo-info)",
          "info-pale": "var(--creo-info-pale)",
        },
      },
    },
  },
  plugins: [],
};
export default config;
